Cypher builder match patterns
neo4j/graphql pull request #1303
Opened 2022-04-25 14:38 UTC by angrykoala

* Add `Match` statement
* Refactor some of the statements
* Adds `MatchPattern` AST element
* Moves parameters to `MatchPattern`
* Adds named nodes to cypherContext

2022-04-28 08:40 UTC, angrykoala commented on packages/graphql/src/translate/cypher-builder/MatchPattern.ts
> +        this.options = { ...{ labels: true, relationshipTypes: true }, ...options };
Just stylistic choice, happy to change it

2022-04-28 09:46 UTC, angrykoala commented on packages/graphql/src/translate/cypher-builder/CypherBuilder.test.ts
> +        test("Match Node", () => {
Good point, I actually caught a minor typo by this test

2022-04-28 10:01 UTC, angrykoala commented on packages/graphql/src/translate/cypher-builder/CypherBuilder.test.ts
> +        test("Nested Call", () => {
I'm not sure what do you mean by aliases, could you give me an example of the kind of cypher to test?

2022-04-29 13:35 UTC, darrellwarde requested changes
This broadly looks good, have just selected "Request changes" so that I can get answers to these questions before we merge?

2022-04-29 13:35 UTC, darrellwarde commented on examples/neo-push/server/tsconfig.json
> +{
_Another_ config file? 😉  Where has this come from? 👀

2022-04-29 13:35 UTC, darrellwarde commented on packages/graphql/tests/tck/tck-test-files/connections/connect-or-create/connect-or-create-auth.test.ts
> +                MERGE (this0_genres_connectOrCreate_this2:\`Genre\` { name: $this0_genres_connectOrCreate_param0 })
I've heard about arguments between starting counting at 0 or 1, but starting count at 2?! What's the cause of this?

2022-04-29 13:35 UTC, darrellwarde commented on packages/graphql/src/translate/cypher-builder/statements/Match.ts
> +    // parameters cast required due to neo-push
Hold on... We're having to add changes to our _production code_... Because of `neo-push`?!

2022-05-05 12:33 UTC, darrellwarde approved these changes
I would say this is probably good to go now!

2022-05-05 12:49 UTC, merged