Subscription example
neo4j/graphql pull request #1460
Opened 2022-05-23 11:12 UTC by angrykoala

# Description
An example for local subscriptions

2022-05-27 13:19 UTC, darrellwarde requested changes
Broadly looks good! Currently included the neo place work, so let's merge that first. A few suspected copy/paste errors.

2022-05-27 13:19 UTC, darrellwarde commented on examples/subscriptions/typedefs.graphql
> +    released:Int
Sorry for being pedantic, this hurts my life. 😆 

```suggestion
    released: Int
```

2022-05-27 13:19 UTC, darrellwarde commented on examples/subscriptions/package.json
> +    "name": "neo-place",
Needs a new name!

2022-05-27 13:19 UTC, darrellwarde commented on examples/subscriptions/database-setup.js
> +}
Copy and paste?

2022-05-27 13:19 UTC, darrellwarde commented on examples/subscriptions/create-plugin.js
> +    return new SubscriptionsPlugin();
We can use the single instance one now right?

2022-05-27 13:19 UTC, darrellwarde commented on examples/subscriptions/server.js
> +    await neoSchema.assertIndexesAndConstraints({ options: { create: true } });
Probably not necessary in this example?

2022-08-31 15:46 UTC, angrykoala commented
Stale PR, neo/place was already merged

2022-08-31 15:46 UTC, closed without merging