Fix: Mutation on Interface fail to keep one to one constraint
neo4j/graphql pull request #1506
Opened 2022-06-01 14:11 UTC by tbwiss

# Description

This fix adds two validations for the situations outlined in #1430.
- Create: For a one-to-one relationship it should throw an error if more than one node wants to be created: `packages/graphql/src/translate/create-create-and-params.ts`.
- Update: Should not allow adding/creating a second node to an existing one-to-one relationship: `packages/graphql/src/translate/translate-update.ts`.

The wording of the error message can definitely be discussed!

# Issue

Addresses: #1430 

Closes:

- #1430 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] New files have copyright header

2022-06-15 10:41 UTC, darrellwarde requested changes
I _think_ there might still be a few cases where this falls over:

- `connect` operations
- `create` operations within a nested update - does the Cypher validation also need go in `create-update-and-params.ts` for the nested case?

We can either address these now or raise them as separate bug reports.

2022-06-15 13:38 UTC, tbwiss commented
@darrellwarde with https://github.com/neo4j/graphql/pull/1506/commits/63b830efa169fcdf6cfa53531890eaf42b57f609 I added some additional tests for `connect` and `create`. I'm however not sure if this is the best solution to solve it thou,

2022-06-28 15:24 UTC, darrellwarde approved these changes
Apart from my small comment around the error message wording, this is looking really great! Super well tested! 🏆

2022-06-28 15:24 UTC, darrellwarde commented on packages/graphql/src/translate/create-create-and-params.ts
> +                            }" cannot have more than one node linked`
Just a suggestion about error message wording here, would be good to also have the typename in the error message. 🙂 

```suggestion
                            `Relationship field "${node.name}.${
                                relationField.interface?.dbPropertyName || relationField.interface?.fieldName
                            }" cannot have more than one node linked`
```

2022-06-29 07:36 UTC, merged