Docs: Migration guide - schema configuration
neo4j/graphql pull request #1507
Opened 2022-06-01 15:03 UTC by tbwiss

# Description

Add additional helpful information to the migration guide regarding the schema configuration.
Creds to @jharris4!

2022-06-01 19:19 UTC, jharris4 commented
  🚀

2022-06-02 07:27 UTC, mjfwebb requested changes
Nice! Small suggestions to make it clearer which examples are related (and for search-ability).

2022-06-02 07:27 UTC, mjfwebb commented on docs/modules/ROOT/pages/guides/migration-guide/server.adoc
> +Or like this for the second case:
```suggestion
Or to exclude queries for a specific type like so:
```

2022-06-02 08:25 UTC, neo4j-team-graphql commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-1507.surge.sh
<!-- Sticky Pull Request Comment -->

2022-06-02 08:42 UTC, mjfwebb submitted a review, later dismissed

2022-06-02 11:23 UTC, merged