Feature/1100 extra custom scalar where fields
neo4j/graphql pull request #2175
Opened 2022-10-04 14:23 UTC by Liam-Doodson

# Description

Added the following extra where fields for custom scalars:
* For a list field: _NOT, _INCLUDES and _NOT_INCLUDES
* For a singular field: _NOT, _IN and _NOT_IN

Updated schema tests to check for these extra fields.
Added integration tests to test filtering with the extra fields.

# Issue

Closes #1100 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

2022-10-04 14:26 UTC, neo4j-team-graphql commented
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at
 http://neo4j-graphql-toolbox-stage-2175.surge.sh (=> for local development; use for instance [Neo4j Desktop](https://neo4j.com/download/))
or
 https://neo4j-graphql-toolbox-stage-2175.surge.sh (=> use to connect to an [Aura Free](https://neo4j.com/cloud/aura-free/) dbms)
<!-- Sticky Pull Request Comment -->

2022-10-04 16:22 UTC, darrellwarde requested changes
One change that is definitely needed is the addition of a changeset for this work - you do this by going to the root of your cloned repo and running `yarn changeset`, which will launch a wizard to walk you through adding a changelog entry and specifying the version. This should be within the development documentation, that's on us.

Other than that, some general feedback is you have added lots of tests (which is great!), however, they are all for positive cases where the result matches the filter. It would be good to see some tests where there are zero expected results which match the filter, in case for some reason the result is _always_ returned. But this isn't a blocker!

Nice work, you figured out where to add this in quickly. 🙂

2022-10-05 08:56 UTC, Liam-Doodson commented on packages/graphql/tests/integration/custom-scalar-filtering.int.test.ts
> +        process.env.NEO4J_GRAPHQL_ENABLE_REGEX = "true";
Ah yes I meant to delete those lines!

2022-10-05 15:07 UTC, darrellwarde approved these changes
All looks good to me, nice work!

2022-10-05 15:07 UTC, darrellwarde commented on .changeset/thick-boats-peel.md
> +Added extra where fields for custom scalars. For lists of custom scalars \_NOT, \_INCLUDES and \_NOT_INCLUDES are now supported. For a single value custom scalars \_NOT, \_IN and \_NOT_IN are now sup
Excellent changelog entry! 👏

2022-10-05 15:10 UTC, Liam-Doodson commented on .changeset/thick-boats-peel.md
> +Added extra where fields for custom scalars. For lists of custom scalars \_NOT, \_INCLUDES and \_NOT_INCLUDES are now supported. For a single value custom scalars \_NOT, \_IN and \_NOT_IN are now sup
Thank you!

2022-10-05 15:26 UTC, merged