fix 2377
neo4j/graphql pull request #2407
Opened 2022-11-11 17:22 UTC by MacondoExpress

# Includes enums in onCreateInput types

# Issue

`Closes #2377

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

2022-11-11 17:26 UTC, neo4j-team-graphql commented
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at
 https://neo4j-graphql-toolbox-stage-2407.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Comment -->

2022-11-14 06:28 UTC, tbwiss submitted a review, later dismissed
LGTM! Thanks @MacondoExpress!

2022-11-14 07:37 UTC, mjfwebb requested changes

2022-11-14 07:37 UTC, mjfwebb commented on packages/graphql/tests/schema/enum.test.ts
>              type Movie {
Can you please remove this change?

2022-11-14 09:08 UTC, MacondoExpress commented on packages/graphql/tests/schema/enum.test.ts
>              type Movie {
Sure!

2022-11-14 09:31 UTC, mjfwebb approved these changes
Great, thanks!

2022-11-14 09:44 UTC, merged