Add changes from #1099, non breaking and with integration test
neo4j/graphql pull request #2503
Opened 2022-12-01 16:05 UTC by darrellwarde

# Description

> **Note**
> 
> Please provide a description of the work completed in this PR below

Allows scalars to accept Neo4j types rather than strings only for temporal types - better compatibility with OGM.

## Complexity

> **Note**
>
> Please provide an estimated complexity of this PR of either Low, Medium or High

Complexity: Low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Supersedes #1099

2022-12-01 16:09 UTC, neo4j-team-graphql commented
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2503.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Comment -->

2022-12-05 09:44 UTC, mjfwebb requested changes

2022-12-05 09:44 UTC, mjfwebb commented on packages/ogm/tests/integration/scalars.int.test.ts
> +describe("pluralize with underscore", () => {
Description needs to be updated :)

2022-12-05 10:06 UTC, darrellwarde commented on packages/ogm/tests/integration/scalars.int.test.ts
> +describe("pluralize with underscore", () => {
Good spot, thanks!

2022-12-05 10:09 UTC, mjfwebb approved these changes
Looks great! :+1:

2022-12-05 10:16 UTC, merged