add Graphql-playground-middleware-express
neo4j/graphql pull request #261
Opened 2021-06-16 02:36 UTC by Rohcode

# Description
Adding development GraphQL Playground.

2021-06-16 07:30 UTC, danstarns requested changes
Thank you for this, looks good and works just fine. Two comments I added and just to point out you will need to sign our CLA agreement http://neo4j.com/developer/cla

2021-06-16 07:30 UTC, danstarns commented on examples/neo-push/server/src/server.ts
> +    const expressPlayground = require('graphql-playground-middleware-express').default
Could we use the `import` syntax here to be consistent with the rest of the codebase?

2021-06-16 07:30 UTC, danstarns commented on examples/neo-push/server/package.json
> +        "graphql-playground-middleware-express": "^1.7.22",
Please could you pin this: 

```
"graphql-playground-middleware-express": "1.7.22",
```

Pining the dependencies means we reduce the chance of things breaking on version increments.

2021-06-19 00:40 UTC, Rohcode reviewed
Yep

2021-06-28 10:54 UTC, oskarhane commented
@Rohcode Hi, I can't find your CLA signature. Did you send it to us?
http://neo4j.com/developer/cla

2021-06-29 06:46 UTC, Rohcode commented
Hi. My name is Rohan Thompson ***@***.***, Rohcode)
I agree to the terms in the attached Neo4j Contributor License Agreement with the edit clarifying that contributions are restricted to Neo4j Github projects (see attached).

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Monday, June 28th, 2021 at 20:54, Oskar Hane ***@***.***> wrote:

> [@Rohcode](https://github.com/Rohcode) Hi, I can't find your CLA signature. Did you send it to us?
> http://neo4j.com/developer/cla
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/neo4j/graphql/pull/261#issuecomment-869583616), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AJH2RUHB7HE5MONEDJC6XGDTVBIFLANCNFSM46YOFBOQ).

2021-06-29 08:55 UTC, oskarhane commented
> Hi. My name is Rohan Thompson ***@***.***, Rohcode) I agree to the terms in the attached Neo4j Contributor License Agreement with the edit clarifying that contributions are restricted to Neo4j Github projects (see attached). Sent with [ProtonMail](https://protonmail.com/) Secure Email. ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
> […](#)

Sorry for the back and forth with this, but we're going to need you to send the CLA email to the adress specified on http://neo4j.com/developer/cla

The email is in the last section on that page.

2021-06-30 12:13 UTC, oskarhane commented
I see that you've signed the CLA now, thanks for that. The next hurdle is that the there's nothing in the committers info that can be tied to your GH user - so our white listing system (that whitelists GH users) don't know that you (your GH user) made the committs.
Could you re-commit using a git user config using the same email address as your GH user @Rohcode?

So sorry for the inconvenience.

2021-06-30 12:45 UTC, Rohcode commented
Sorry I'm confused...
I used @Rohcode (my GH account tied to this email) to make the neo-push pull request...Thought that was how you got this email.. It was a small commit, just integrated GraphQL playground for express..

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Wednesday, June 30th, 2021 at 22:13, Oskar Hane ***@***.***> wrote:

> I see that you've signed the CLA now, thanks for that. The next hurdle is that the there's nothing in the committers info that can be tied to your GH user - so our white listing system (that whitelists GH users) don't know that you (your GH user) made the committs.
> Could you re-commit using a git user config using the same email address as your GH user [@Rohcode](https://github.com/Rohcode)?
>
> So sorry for the inconvenience.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/neo4j/graphql/pull/261#issuecomment-871350477), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AJH2RUFZ4W5RVEFO4EJIMV3TVMC77ANCNFSM46YOFBOQ).

2021-07-28 07:47 UTC, darrellwarde commented
Closing due to inactivity and the fact that commits were not made using git configured with the same details as user's GitHub account.

2021-07-28 07:47 UTC, closed without merging