add assertIndexesAndConstraints on OGM
neo4j/graphql pull request #3117
Opened 2023-03-29 17:58 UTC by g10

# Description

`assertIndexesAndConstraints` is not available on the OGM class, therefore it's required to add the `@neo4j/graphql` package (in addition to `@neo4j/graphql-ogm`) to add the indexes and constraints specified in the schema

more details → https://github.com/neo4j/graphql/issues/3116

## Complexity

Complexity: Low

# Issue

Closes https://github.com/neo4j/graphql/issues/3116 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [ ] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

2023-03-29 17:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/neo4j/graphql?pullRequest=3117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neo4j/graphql?pullRequest=3117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neo4j/graphql?pullRequest=3117) it.</sub>

2023-03-31 13:12 UTC, darrellwarde commented
Hey @g10, thanks for the contribution! A few things:

- Thanks for sending the email signing the CLA. We're also trialling a new system at the moment, so if you would mind clicking the button in the comment from @CLAassistant and signing there also, it would be appreciated.
- Please add a changeset by running `yarn changeset` in the root of the repo, following the instructions and adding an appropriate changelog message.
- If possible, please add at least one integration test for this functionality. I realise that it is tested in the library itself and the OGM isn't all that well tested, but we need to be aiming to improve test coverage here.

Thanks again, I look forward to seeing this progress!

2023-03-31 18:05 UTC, g10 commented
hi @darrellwarde, added the change requests, let me know if this works

2023-05-24 10:23 UTC, neo4j-team-graphql commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-3117.surge.sh
<!-- Sticky Pull Request Commentdocs -->

2023-05-25 10:31 UTC, darrellwarde requested changes
I'm so sorry about the slow review on this one - I would like to see the new code tweaked a bit, but the feature is a nice addition!

2023-05-28 23:04 UTC, g10 commented on packages/ogm/tests/integration/neo4j.ts
> +    const { NEO_USER = "neo4j", NEO_PASSWORD = "NeedsALongPassword", NEO_URL = "neo4j://localhost:7687/neo4j" } = process.env;
true, guess I've aligned it with the one in [`docker-compose.yaml`](https://github.com/neo4j/graphql/blob/dev/docker-compose.yaml) but there's no need for that as it is the default 😁

2023-06-27 12:05 UTC, darrellwarde approved these changes

2023-06-27 14:11 UTC, merged