Update relationships.adoc
neo4j/graphql pull request #3271
Opened 2023-05-03 16:53 UTC by ogoldberg

documentation tweak: make it more clear that the relationship interface is not required to live on both sides of the relationship

# Description

> **Note**
> 
> Please provide a description of the work completed in this PR below
documentation tweak: make it more clear that the relationship interface is not required to live on both sides of the relationship

## Complexity

> **Note**
>
> Please provide an estimated complexity of this PR of either Low, Medium or High

Complexity: low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ x] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

2023-05-04 08:49 UTC, mjfwebb requested changes
Thanks very much for your contribution! Just a small change of wording.

Please also sign our [Contributor License Agreement](https://cla-assistant.io/neo4j/graphql?pullRequest=3271) so that we may accept your contribution.

2023-05-04 08:49 UTC, mjfwebb commented on docs/modules/ROOT/pages/type-definitions/relationships.adoc
> +2. Add a `properties` argument to either or both "sides" of the `@relationship` directive which points to the newly defined interface
I think this is a great point to make, but let's change the wording a little:

```suggestion
2. Add a `properties` argument to both "sides" (or just one side, if you prefer) of the `@relationship` directive which points to the newly defined interface
```

2023-05-04 21:58 UTC, ogoldberg commented
> Thanks very much for your contribution! Just a small change of wording.
> 
> Please also sign our [Contributor License Agreement](https://cla-assistant.io/neo4j/graphql?pullRequest=3271) so that we may accept your contribution.

Thanks! I did send in the email. Just waiting for a response. I tried the link you shared, but even though the page loaded, there wasn't really anything actionable on it.

2023-05-04 22:02 UTC, ogoldberg commented
> Thanks very much for your contribution! Just a small change of wording.
> 
> Please also sign our [Contributor License Agreement](https://cla-assistant.io/neo4j/graphql?pullRequest=3271) so that we may accept your contribution.

Successfully signed. Thanks!

2023-05-05 06:44 UTC, mjfwebb approved these changes
Looks good! Thanks for the contribution.

2023-05-05 07:18 UTC, neo4j-team-graphql commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-3271.surge.sh
<!-- Sticky Pull Request Commentdocs -->

2023-05-05 07:34 UTC, merged