add directives for jwtPayload, include standard fields
neo4j/graphql pull request #3305
Opened 2023-05-09 16:20 UTC by a-alle

# Description

Implements directives: `@jwtPayload`, `@jwtClaim`
Generates filters based on fields in the `@jwtPayload` annotated type + JWT spec Registered Claim Names
No operations are generated for the `@jwtPayload`  annotated type

Validations:
- The `@jwtPayload` directive can be used only once in a user's type definitions.
- The type decorated with `@jwtPayload` will only be allowed to contain fields of primitive types, or their list variants.
- The `@jwtClaim` directive can only be used within the type flagged with the `@jwtPayload` directive.
- Both directives cannot be used in conjunction with other directives

## Complexity

> **Note**
>
> Please provide an estimated complexity of this PR of either Low, Medium or High

Complexity: Low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

2023-05-09 16:25 UTC, neo4j-team-graphql commented
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-3305.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Commenttoolbox -->

2023-05-09 16:39 UTC, neo4j-team-graphql commented
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 40 | 57 | 1134 |
|  aggregations.NestedAggregation | 16553 | 16553 | 127 | 112 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 98 | 81 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 3593 | 3171 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 3029 | 2845 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 43 | 77 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 50 | 52 | 2174 |
|  aggregations.DeeplyNestedCount | 13070329 | 13070329 | 4980 | 4595 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 143 | 152 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 74 | 132 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 156 | 242 | 3003 |
|  connections.Connection | 14082 | 14082 | 52 | 79 | 2174 |
|  connections.NestedConnection | 45472 | 45472 | 110 | 144 | 4516 |
|  connections.ConnectionWithSort | 3284 | 3284 | 67 | 85 | 1040 |
|  connections.ConnectionWithSortAndCypher | 3284 | 3284 | 224 | 348 | 1040 |
|  create.SimpleMutation | 7 | 7 | 66 | 127 | 1 |
|  cypher-directive.TopLevelCypherDirective | 122100 | 122100 | 598 | 701 | 12241 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 153617 | 153617 | 193 | 219 | 12241 |
|  delete.SimpleDelete | 19401 | 19401 | 312 | 313 | 1040 |
|  delete.NestedDeleteInUpdate | 23546 | 23546 | 161 | 163 | 2040 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 40 | 122 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 81 | 136 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 3450 | 3450 | 26 | 32 | 1134 |
|  2925.NestedSingleRelationshipRequiredFilter | 9383 | 9383 | 58 | 71 | 1040 |
|  query.SimpleQuery | 16162 | 16162 | 58 | 59 | 2174 |
|  query.QueryWhere | 9713 | 9697 | 37 | 43 | 2166 |
|  query.SimpleQueryWithNestedWhere | 9891 | 9875 | 52 | 63 | 2166 |
|  query.Nested | 10096041 | 10096041 | 10146 | 10539 | 2008534 |
|  query.NestedWithFilter | 10074401 | 10074401 | 10080 | 10555 | 2004000 |
|  query.OrFilterOnRelationships | 41711 | 42497 | 193 | 207 | 1327 |
|  query.OrFilterOnRelationshipsAndNested | 35400 | 36408 | 223 | 253 | 1327 |
|  query.QueryWithNestedIn | 13630 | 13243 | 58 | 63 | 1296 |
|  query.NestedConnectionWhere | 9834 | 9834 | 56 | 74 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9849 | 10044 | 77 | 96 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19062 | 19320 | 138 | 158 | 1570 |
|  query.NestedWithRelationshipSingleFilters | 3732 | 3732 | 169 | 268 | 1134 |
|  query.Fulltext | 80 | 80 | 33 | 35 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 46 | 62 | 84 |
|  sorting.SortMultipleTypes | 3515 | 3515 | 68 | 102 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1516 | 1430 | 232 | 301 | 1040 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 100 | 57 | 2174 |
|  sorting.SortDeeplyNestedFields | 43198 | 43198 | 179 | 99 | 4516 |
|  sorting.SortWithTopLevelCypher | 3121 | 3121 | 136 | 232 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 65 | 81 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 64 | 69 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 306 | 306 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 291 | 333 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 104 | 144 | 2002 |

</details>
        
Old Schema Generation: 46.911s
Schema Generation: 46.321s
Old Subgraph Schema Generation: 1:00.900 (m:ss.mmm)
Subgraph Schema Generation: 1:02.450 (m:ss.mmm)

<!-- Sticky Pull Request Commentperformance -->

2023-05-11 10:20 UTC, MacondoExpress approved these changes

2023-05-12 07:54 UTC, darrellwarde requested changes
We need to think about the whole `makeSchemaToAugment` thing. Other than that, I think the types of the JWT claims need tweaking!

2023-05-12 17:11 UTC, merged