Settable directive
neo4j/graphql pull request #3404
Opened 2023-05-31 14:55 UTC by angrykoala

# Description
> This PR depends on #3403 

Adds `@settable` directive defined in https://github.com/neo4j/graphql/discussions/3263

This directive has the following options:
* onCreate
* onUpdate

Setting these values will disable the generation of the GraphQL input fields for create operations and update operations

## Complexity

Complexity: Medium

2023-05-31 15:14 UTC, neo4j-team-graphql commented
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 38 | 59 | 1134 |
|  aggregations.NestedAggregation | 16553 | 16553 | 75 | 128 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 51 | 71 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 3701 | 4164 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 3471 | 3512 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 56 | 67 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 59 | 82 | 2174 |
|  aggregations.DeeplyNestedCount | 13070331 | 13070331 | 5285 | 6161 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 258 | 234 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 134 | 96 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 212 | 259 | 3003 |
|  connections.Connection | 14082 | 14082 | 66 | 78 | 2174 |
|  connections.NestedConnection | 45472 | 45468 | 123 | 140 | 4516 |
|  connections.ConnectionWithSort | 3284 | 3284 | 76 | 81 | 1040 |
|  connections.ConnectionWithSortAndCypher | 16325 | 16325 | 115 | 120 | 2174 |
|  create.SimpleMutation | 7 | 7 | 60 | 71 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 32 | 43 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 314 | 296 | 1040 |
|  delete.NestedDeleteInUpdate | 19198 | 19198 | 284 | 304 | 1183 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 50 | 56 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 112 | 137 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 46 | 49 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 66 | 84 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 26 | 35 | 1040 |
|  query.SimpleQueryWithRelationship | 16162 | 16162 | 58 | 54 | 2174 |
|  query.QueryWhere | 9704 | 9706 | 46 | 48 | 2164 |
|  query.SimpleQueryWithNestedWhere | 9882 | 9884 | 62 | 70 | 2164 |
|  query.Nested | 10096041 | 10096041 | 10861 | 11479 | 2008534 |
|  query.NestedWithFilter | 10074401 | 10074401 | 11294 | 11178 | 2004000 |
|  query.OrFilterOnRelationships | 43800 | 43665 | 210 | 521 | 2006 |
|  query.OrFilterOnRelationshipsAndNested | 37677 | 37540 | 273 | 439 | 2006 |
|  query.QueryWithNestedIn | 13427 | 13686 | 64 | 83 | 1226 |
|  query.NestedConnectionWhere | 9834 | 9834 | 67 | 95 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9898 | 10089 | 106 | 127 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19098 | 19308 | 260 | 202 | 1580 |
|  query.NestedWithRelationshipSingleFilters | 3881 | 3881 | 254 | 269 | 1134 |
|  query.Fulltext | 80 | 80 | 35 | 49 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 60 | 82 | 84 |
|  sorting.SortMultipleTypes | 3515 | 3515 | 100 | 96 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14558 | 14527 | 108 | 122 | 2174 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 77 | 61 | 2174 |
|  sorting.SortDeeplyNestedFields | 43198 | 43198 | 109 | 138 | 4516 |
|  sorting.SortWithTopLevelCypher | 16162 | 16162 | 64 | 70 | 2174 |
|  unions.SimpleUnionQuery | 321 | 321 | 75 | 79 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 72 | 76 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 313 | 367 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 367 | 389 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 192 | 186 | 2002 |

</details>
        
Old Schema Generation: 54.117s
Schema Generation: 53.892s
Old Subgraph Schema Generation: 1:10.180 (m:ss.mmm)
Subgraph Schema Generation: 1:11.319 (m:ss.mmm)

<!-- Sticky Pull Request Commentperformance -->

2023-06-02 10:10 UTC, Liam-Doodson requested changes

2023-06-02 10:10 UTC, Liam-Doodson commented on packages/graphql/src/schema/create-relationship-fields/create-relationship-fields.ts
> +        if (nestedOperations.has(RelationshipNestedOperationsOption.CREATE) && rel.settableOptions.onCreate) {
I can see from the schema tests that `@settable` is also removing nested operations which are only supposed to be controlled by the `@relationship(nestedOperations: [])`. I imagine these are the lines that are causing this

```suggestion
        if (nestedOperations.has(RelationshipNestedOperationsOption.CREATE)) {
```

2023-06-02 10:10 UTC, Liam-Doodson commented on packages/graphql/src/schema/create-relationship-fields/create-relationship-fields.ts
> +        if (nestedOperations.has(RelationshipNestedOperationsOption.UPDATE) && rel.settableOptions.onUpdate) {
Same as above

```suggestion
        if (nestedOperations.has(RelationshipNestedOperationsOption.UPDATE)) {
```

2023-06-02 10:10 UTC, Liam-Doodson commented on packages/graphql/tests/schema/directives/settable.test.ts
> +describe("@settable", () => {
Seeing as this is quite interlinked with `@relationship` `nestedOperations` it might be worth adding some tests that combine the two

2023-06-02 10:40 UTC, Liam-Doodson commented on packages/graphql/tests/schema/directives/settable.test.ts
> +                  connect: [ActorActedInConnectFieldInput!]
The nested create argument should still be here

2023-06-02 12:34 UTC, Liam-Doodson requested changes

2023-06-02 12:34 UTC, Liam-Doodson commented on packages/graphql/tests/schema/directives/settable.test.ts
> +                  actedIn: [ActorActedInUpdateFieldInput!]
Sorry, I probably told you to change the wrong line, this is the field that should be removed by `onUpdate: false`. Currently, the schema here doesn't change if you set `onUpdate: true`

```suggestion
```

2023-06-02 13:24 UTC, Liam-Doodson approved these changes
LGTM!

2023-06-02 14:01 UTC, merged