Remove surplus _IN and _NOT_IN filters for relationships
neo4j/graphql pull request #400
Opened 2021-08-09 13:23 UTC by darrellwarde

# Description

Let's take the opportunity of this breaking release to remove some surplus requirements, `_IN` and `_NOT_IN` for one-to-many and one-to-one relationships. We don't currently treat these relationship cardinalities differently anywhere else, the filters are completely untested, and the same filters can be achieved through other means (see migration guide for example).

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

2021-08-09 14:00 UTC, danstarns requested changes
If we are going to remove them, Let's remove them for good. You have forgotten about the code behind these [here](https://github.com/neo4j/graphql/blob/2.0.0/packages/graphql/src/translate/create-where-and-params.ts#L71) and [here](https://github.com/neo4j/graphql/blob/2.0.0/packages/graphql/src/translate/create-where-and-params.ts#L190). I'm not sure I completely understand the reasoning for removing them and if they work just fine why are we getting rid?

2021-08-09 15:22 UTC, darrellwarde commented
> If we are going to remove them, Let's remove them for good. You have forgotten about the code behind these [here](https://github.com/neo4j/graphql/blob/2.0.0/packages/graphql/src/translate/create-where-and-params.ts#L71) and [here](https://github.com/neo4j/graphql/blob/2.0.0/packages/graphql/src/translate/create-where-and-params.ts#L190). I'm not sure I completely understand the reasoning for removing them and if they work just fine why are we getting rid?

Honestly, I don't think the Cypher for them is even correct (wrong predicate), and we really shouldn't have any untested paths in our code. I was able to remove these two filters and only 1 (!) TCK test broke - I don't think that's really the level of quality we should be aiming for.

2021-08-10 07:41 UTC, oskarhane approved these changes
LGTM

2021-08-10 07:41 UTC, danstarns approved these changes

2021-08-10 07:51 UTC, merged