Fixes the missing takeover of custom directives for interfaces and connection fields
neo4j/graphql pull request #4509
Opened 2024-01-12 18:25 UTC by Andy2003

# Description

Fixes the missing takeover of custom directives for interfaces and connection fields

## Complexity

> **Note**
>
> Please provide an estimated complexity of this PR of either Low, Medium or High

Complexity: low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [x] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

2024-01-12 18:29 UTC, neo4j-team-graphql commented
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4509.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Commenttoolbox -->

2024-01-16 15:14 UTC, Andy2003 commented
I extracted the refactoring part into #4516

2024-01-29 11:43 UTC, angrykoala requested changes

2024-01-29 11:43 UTC, angrykoala commented on packages/graphql/src/schema-model/library-directives.ts
> +    ...(Object.keys(annotationsParsers) as LibraryDirectives[])
Looks good, my only comment would be to change this type to ` as Array<keyof Annotations>` so it is a bit more accurate

2024-01-29 13:39 UTC, angrykoala approved these changes

2024-01-29 13:40 UTC, merged