fix: #4514 augment interfaces the same way no matter if they are used as the target of a relationship or not
neo4j/graphql pull request #4515
Opened 2024-01-16 14:45 UTC by Andy2003

# Description

augment interfaces the same way no matter if they are used as the target of a relationship or not

## Complexity

Complexity: Low

# Issue

Closes #4514

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [x] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

2024-01-16 14:49 UTC, neo4j-team-graphql commented
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4515.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Commenttoolbox -->

2024-01-26 17:23 UTC, a-alle requested changes
Contribution much appreciated! Let's get the user defined interface directives on the generated type and get this in.

2024-01-26 17:23 UTC, a-alle commented on packages/graphql/tests/schema/interfaces.test.ts
> +            interface MovieNode {
the directive is missing here, user defined directives are not propagated anymore

2024-01-26 17:23 UTC, a-alle commented on packages/graphql/src/schema/make-augmented-schema.ts
> -                config: {
I think this argument is obsolete now and can be removed

2024-01-26 17:23 UTC, a-alle commented on packages/graphql/src/schema/make-augmented-schema.ts
> -            const userDefinedInterfaceDirectives = userDefinedDirectivesForInterface.get(entity.name) || [];
these directives are not handled anymore (`MovieNode` case in the tests)

2024-01-26 19:09 UTC, Andy2003 commented
The tests are currently failing b/c of a bug I fixed in https://github.com/neo4j/graphql/pull/4509, wich should be merged 1st

2024-01-26 19:10 UTC, Andy2003 commented
The tests are currently failing b/c of a bug I fixed in https://github.com/neo4j/graphql/pull/4509, wich should be merged 1st

2024-01-29 15:01 UTC, a-alle approved these changes

2024-01-29 15:02 UTC, merged