Minimum node version 18
neo4j/graphql pull request #4596
Opened 2024-01-26 13:34 UTC by mjfwebb

# Description

Node.js 16's is [now considered End of Life](https://nodejs.org/en/blog/announcements/nodejs16-eol/), so we are dropping support for it in favour of LTS Node 18.

## Complexity

Low

2024-01-26 13:39 UTC, neo4j-team-graphql commented
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4596.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Commenttoolbox -->

2024-01-29 10:02 UTC, MacondoExpress approved these changes

2024-01-30 10:22 UTC, darrellwarde requested changes

2024-01-30 10:22 UTC, darrellwarde commented on .changeset/dry-cups-dream.md
> +"server_perf": major
```suggestion
```

2024-02-14 11:54 UTC, closed without merging