refactoring: Harmonizing AggregationSelection-types
neo4j/graphql pull request #4661
Opened 2024-02-06 17:04 UTC by Andy2003

# Description

After #4623 the `*AggregateSelectioNonNullable` types, have no more differences to the `*AggregateSelectioNullable` types. This Commit removes the `(Non)Nullable`-suffix from the augmented types.

## Complexity

Complexity: low

# Issue

Closes #4615

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [x] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

2024-02-06 17:07 UTC, neo4j-team-graphql commented
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4661.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Commenttoolbox -->

2024-02-07 10:48 UTC, angrykoala requested changes
Looks good to me,  just the changeset change

2024-02-07 10:48 UTC, angrykoala commented on .changeset/fair-meals-reflect.md
> +The old `*AggregateSelectioNonNullable`-types and `*AggregateSelectioNullable`-types are now merged into `*AggregateSelectio`-types`.
Instead of changing the existing changeset, please make a new one. This is to make sure that the resulting changelog points to the correct PRs

2024-02-07 10:48 UTC, angrykoala commented on packages/graphql/src/schema-model/attribute/model-adapters/AttributeAdapter.ts
> +        return `${this.getFieldTypeName()}AggregateSelection`;
:clap:

2024-02-07 11:43 UTC, angrykoala approved these changes

2024-02-07 11:54 UTC, darrellwarde approved these changes
LGTM, just a small typo in the changeset!

2024-02-07 11:54 UTC, darrellwarde commented on .changeset/violet-walls-travel.md
> +The old `*AggregateSelectioNonNullable`-types and `*AggregateSelectioNullable`-types are now merged into `*AggregateSelectio`-types`.
```suggestion
The old `*AggregateSelectionNonNullable`-types and `*AggregateSelectionNullable`-types are now merged into `*AggregateSelection`-types`.
```

2024-02-07 13:14 UTC, darrellwarde approved these changes
LGTM. It would be appreciated if you could not squash commits - it makes it easier to review when we can see the exact changes in a commit in response to one of our comments. 🙂

2024-02-07 13:15 UTC, merged