Make relationshipProperties error messages more helpful
neo4j/graphql pull request #4674
Opened 2024-02-08 14:21 UTC by mjfwebb

2024-02-08 14:23 UTC, neo4j-team-graphql commented
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4674.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Commenttoolbox -->

2024-02-08 14:28 UTC, darrellwarde requested changes
Looks generally good, just a comment around one of the error messages!

2024-02-08 14:28 UTC, darrellwarde commented on packages/graphql/src/schema/validation/custom-rules/directives/relationship.ts
> +                    `@relationship.properties invalid. @relationship.properties must be applied to an interface. Note, since version 5.0.0, the @relationshipProperties directive must be applied to a
Middle sentence is a bit weird! Maybe:

```suggestion
                    `@relationship.properties invalid. The @relationshipProperties directive must be applied to a type and not an interface, a breaking change introduced in version 5.0.0.`,
```

???

2024-02-09 11:08 UTC, darrellwarde approved these changes
LGTM!

2024-02-09 12:00 UTC, merged