Add interface relationship aggregate filters
neo4j/graphql pull request #4856
Opened 2024-03-12 11:22 UTC by a-alle

# Description

This PR introduces aggregate filters on an interface relationship. For example, given the typedefs
```graphql
interface Production {
    title: String!
}
type Movie implements Production {
    title: String!
}
type Series implements Production {
    title: String!
}
type Actor {
    name: String!
    actedIn: [Production!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```
The generated filter type (`ActorWhere`) for `Actor` now contains the `actedInAggregate` field:
```graphql
input ActorWhere {
  AND: [ActorWhere!]
  OR: [ActorWhere!]
  actedInAggregate: ActorActedInAggregateInput
  actedIn: ProductionWhere
  actedIn_NOT: ProductionWhere
  actedInConnection: ActorActedInConnectionWhere
  actedInConnection_NOT: ActorActedInConnectionWhere
  name: String
  name_CONTAINS: String
  name_ENDS_WITH: String
  name_IN: [String]
  name_NOT: String
  name_NOT_CONTAINS: String
  name_NOT_ENDS_WITH: String
  name_NOT_IN: [String]
  name_NOT_STARTS_WITH: String
  name_STARTS_WITH: String
}
```

## Complexity

Complexity: Low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

2024-03-12 11:25 UTC, neo4j-team-graphql commented
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4856.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.
<!-- Sticky Pull Request Commenttoolbox -->

2024-03-12 17:03 UTC, neo4j-team-graphql commented
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3404 | 3404 | 33 | 43 | 1134 |
|  aggregations.TopLevelAggregateWithMultipleFields | 6802 | 6802 | 50 | 53 | 1134 |
|  aggregations.NestedAggregation | 16544 | 16544 | 56 | 73 | 2174 |
|  aggregations.AggregationWithWhere | 11970 | 11970 | 37 | 51 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116478 | 22116478 | 2119 | 2176 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116478 | 22116478 | 2123 | 2216 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9701 | 9701 | 31 | 37 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9928 | 9928 | 34 | 40 | 2174 |
|  aggregations.DeeplyNestedCount | 11062184 | 11062184 | 2886 | 2927 | 2008534 |
|  aggregations.InterfacesAggregations | 6242 | 6242 | 45 | 51 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 11444 | 11444 | 73 | 102 | 2080 |
|  batch-create.BatchCreate | 4200 | 4200 | 169 | 171 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 89 | 66 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 181 | 181 | 3003 |
|  connections.Connection | 14049 | 14049 | 98 | 68 | 2174 |
|  connections.NestedConnection | 41068 | 41068 | 128 | 160 | 4516 |
|  create.SimpleMutation | 7 | 7 | 48 | 57 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 29 | 26 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 228 | 212 | 1040 |
|  delete.NestedDeleteInUpdate | 19165 | 19165 | 174 | 169 | 1183 |
|  2871.NestedRelationshipFilter | 23068 | 23095 | 83 | 67 | 4430 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 44 | 42 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22891 | 22891 | 68 | 97 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 38 | 50 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 47 | 68 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 17 | 25 | 1040 |
|  query.SimpleQueryWithRelationship | 16129 | 16129 | 35 | 44 | 2174 |
|  query.QueryWhere | 9668 | 9690 | 36 | 37 | 2159 |
|  query.SimpleQueryWithNestedWhere | 9835 | 9857 | 43 | 58 | 2159 |
|  query.Nested | 10095502 | 10095502 | 6984 | 6991 | 2008534 |
|  query.NestedWithFilter | 10074351 | 10074351 | 6699 | 6748 | 2004000 |
|  query.OrFilterOnRelationships | 42982 | 41413 | 136 | 156 | 1787 |
|  query.OrFilterOnRelationshipsAndNested | 36247 | 34891 | 260 | 244 | 1787 |
|  query.QueryWithNestedIn | 13388 | 13665 | 64 | 58 | 1221 |
|  query.NestedConnectionWhere | 9801 | 9801 | 59 | 57 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9898 | 9913 | 91 | 79 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 18776 | 18812 | 147 | 160 | 1596 |
|  query.NestedWithRelationshipSingleFilters | 3865 | 3865 | 157 | 198 | 1134 |
|  query.Fulltext | 64 | 64 | 27 | 40 | 16 |
|  query.FulltextWithNestedQuery | 558 | 558 | 37 | 50 | 84 |
|  sorting-and-cypher.TopLevelSortWithCypher | 14059 | 14059 | 37 | 43 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypher | 14059 | 14059 | 60 | 63 | 2174 |
|  sorting-and-cypher.TopLevelSortWithCypherWithNested | 14204 | 14204 | 51 | 71 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypherWithNested | 14204 | 14204 | 88 | 99 | 2174 |
|  sorting-and-cypher.TopLevelSortWithExpensiveCypher | 14931 | 14935 | 94 | 112 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithExpensiveCypher | 14404 | 14404 | 110 | 142 | 2174 |
|  sorting.SortMultipleTypes | 3498 | 3498 | 102 | 89 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14504 | 14504 | 97 | 109 | 2174 |
|  sorting.SortOnNestedFields | 14049 | 14049 | 63 | 46 | 2174 |
|  sorting.SortDeeplyNestedFields | 43148 | 43148 | 77 | 81 | 4516 |
|  sorting.ConnectionWithSort | 3281 | 3281 | 68 | 74 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 53 | 61 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 52 | 57 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 266 | 286 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 245 | 245 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 88 | 107 | 2002 |

</details>
        
Old Schema Generation: 26.244s
Schema Generation: 27.164s
Old Subgraph Schema Generation: 29.738s
Subgraph Schema Generation: 31.463s

<!-- Sticky Pull Request Commentperformance -->

2024-03-13 12:49 UTC, angrykoala requested changes

2024-03-13 12:49 UTC, angrykoala commented on packages/graphql/src/translate/queryAST/ast/filters/aggregation/AggregationPropertyFilter.ts
> +    private shouldResolveAlias() {
A few things here:
* A nitpick, the return type is missing
* The name seems incorrect, shouldResolveAlias feels like it should return a boolean and yet it return the actual map
* This logic feels like it could be in the schemaModel (or adapters, or as a separate utility) as it doesn't deal with cypher translation directly

2024-03-13 12:49 UTC, angrykoala commented on packages/graphql/src/translate/queryAST/ast/filters/aggregation/AggregationPropertyFilter.ts
> +    private resolveDatabaseName(
I'm not sure if resolveDatabaseName is the best name for this, as it is returning a CASE statement and it sounds like it returns a string

Maybe this could be something a bit like "generateFieldPerAliasedName" ?

2024-03-15 17:56 UTC, a-alle commented on packages/graphql/src/schema-model/entity/model-adapters/InterfaceEntityAdapter.ts
> +                concreteLabelsToAttributeAlias.set(concreteEntity.getLabels().join(":"), attributeDatabaseName);
@angrykoala is there a utility for labels.join(":")? Or is the translation layer in general mainly using the "main" label?

2024-03-18 14:34 UTC, merged