Document usage with Next.js
neo4j/graphql pull request #502
Opened 2021-09-21 09:18 UTC by oskarhane

# Description

This adds a guide on how to use this library in a Next.js fullstack application.  
It also adds tests for the code in the guide so it doesn't become outdated.

# Checklist

- [X] Documentation has been updated

2021-09-21 09:19 UTC, neo4j-team-graphql commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-502.surge.sh
<!-- Sticky Pull Request Comment -->

2021-09-21 10:24 UTC, oskarhane commented
There's an issue with the file includes in the docs build system, I've reached out to the docs team to figure out why - it works fine locally.

2021-09-21 13:54 UTC, oskarhane commented
The includes in the docs now work as expected.

2021-09-22 12:42 UTC, angrykoala approved these changes

2021-09-22 12:42 UTC, angrykoala commented on docs/modules/ROOT/pages/guides/frameworks/nextjs.adoc
> +This page describes the basics on how to use `@neo4j/graphql` as part of a https://nextjs.org[Next.js] fullstack application.
Maybe fullstack is a bit redundant if already talking about next.js :thinking: ?
```suggestion
This page describes the basics on how to use `@neo4j/graphql` as part of a https://nextjs.org[Next.js] application.  
```

2021-09-22 15:36 UTC, darrellwarde requested changes
Looks good! Just a small typo which needs correcting.

2021-09-22 15:36 UTC, darrellwarde commented on docs/modules/ROOT/pages/guides/frameworks/nextjs.adoc
> +Make sure you have a Neo4j DBMS running on the configured URI below. Download https://neo4j.com/download[Neo4j Desktop] for easy management of local Neo4j DBMS:s.
I'm guessing "DBMS:s" is a typo - I hate pluralising acronyms so an alternative wording suggestion below!

```suggestion
Make sure you have a Neo4j DBMS running on the configured URI below. Download https://neo4j.com/download[Neo4j Desktop] for easy local Neo4j DBMS management.
```

2021-09-23 09:11 UTC, darrellwarde approved these changes
LGTM, love that we're adding these kind of guides in!

2021-09-23 10:37 UTC, merged