Fix/not null field aggregations
neo4j/graphql pull request #605
Opened 2021-11-23 12:13 UTC by angrykoala

# Description

This PR splits the aggregation base types (e.g. `StringAggregateSelection`) into `Nullable` and `NonNullable` versions, depending on the base type (e.g. String or String!) a more accurate type will be selected, allowing for nullable fields to be used in aggregations. The related issue has an example of this issue

## Other changes
 
* Aggregation types extracted from `make-augmented-schema` and moved to a new class `AggregationTypesMapper` to simplify the process of getting the correct type
* Several schema tests have been updated

# Issue

#594

2021-11-23 17:12 UTC, darrellwarde requested changes
Just one comment! Then a bit of a nasty merge to be done!

2021-11-24 09:42 UTC, angrykoala commented on packages/graphql/src/schema/aggregations/aggregation-types-mapper.ts
> +    private requiredAggregationSelectionTypes: Record<string, ObjectTypeComposer<unknown, unknown>>;
Well, we already use required (e.g. `!field.typeMeta.required`) and 2 variables `nullableAggregationSelectionTypes` and `nonNullableAggregationSelectionTypes` can easily lead to confusion IMO

Happy to change if it is a deal breaker

2021-11-24 16:32 UTC, darrellwarde commented on packages/graphql/src/schema/aggregations/aggregation-types-mapper.ts
> +    private requiredAggregationSelectionTypes: Record<string, ObjectTypeComposer<unknown, unknown>>;
Meeeehhhhh, leave it be!

2021-11-24 16:33 UTC, darrellwarde approved these changes
LGTM! 🙂

2021-11-24 16:49 UTC, merged