Undirected relationships
neo4j/graphql pull request #811
Opened 2022-01-18 14:20 UTC by angrykoala

# Description

This pr adds the argument `directed` to relationship queries. If set to false, the relationship query will be `undirected` (i.e., with the form `()-[]-()`) as defined in [rfc-004](https://github.com/neo4j/graphql/blob/dev/docs/rfcs/rfc-004-undirected-relationship-queries.md)

This is **only** valid for queries, not mutations.

2022-01-19 11:14 UTC, neo4j-team-graphql commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-811.surge.sh
<!-- Sticky Pull Request Comment -->

2022-01-24 18:26 UTC, darrellwarde requested changes
Looks good to me, just a couple of tweaks to the documentation!

2022-01-24 18:26 UTC, darrellwarde commented on docs/modules/ROOT/pages/queries.adoc
> +all related nodes, regardless of the direction of the query. This can be achieved with the argument `directed: false`.
```suggestion
all related nodes, regardless of the direction of the relationship. This can be achieved with the argument `directed: false`.
```

2022-01-24 18:26 UTC, darrellwarde commented on docs/modules/ROOT/pages/queries.adoc
> +Note that _undirected relationships_ are only supported in queries.
```suggestion
Note that _undirected_ relationships are only supported in queries.
```

2022-01-25 09:52 UTC, merged