Async schema generation
neo4j/graphql pull request #896
Opened 2022-01-31 13:49 UTC by darrellwarde

# Description

This PR moves the heavy lifting of the `Neo4jGraphQL` and `OGM` constructors into asynchronous functions, `getSchema()` and `init()`, respectively.

This means that construction will be quick and these functions will have to be awaited following construction. Whilst this may seem like a nuisance right now, in the future this will open doors to more performant schema generation through asynchronous processing.

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

2022-02-04 15:28 UTC, neo4j-team-graphql commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-896.surge.sh
<!-- Sticky Pull Request Comment -->

2022-02-10 15:39 UTC, darrellwarde commented
> Great that this is happening. I guess this means you'll be going for a new major release reasonably soon. Any idea of roughly when the release is scheduled?

Hey @wheresrhys! We wouldn't normally give timelines, but this release has a fairly strict schedule, so you can expect this next week! 🙂 It won't be as much of a jarring release as 3.0.0, but certainly some nice changes to come.

2022-02-10 17:03 UTC, angrykoala requested changes
Overall, the solution looks solid, I just commented on a few style/legibility suggestions and improvements

2022-02-11 11:07 UTC, angrykoala approved these changes

2022-02-11 13:45 UTC, angrykoala approved these changes

2022-02-11 13:45 UTC, angrykoala commented on packages/graphql/tests/integration/custom-resolvers.int.test.ts
> +    test("should accept an array of custom resolvers", async () => {
:clap:

2022-02-11 13:45 UTC, angrykoala commented on packages/graphql/src/classes/Neo4jGraphQL.ts
> +    private wrapResolvers(resolvers: IResolvers, { schema }: { schema: GraphQLSchema }) {
**nitpick (non-blocking)**: Maybe we could move these functions to the bottom?
Usually, it is slightly easier to read functions in a class from more abstract to less abstract (kind of like articles are composed). So, first, we read `generateSchema` at the top, and then, if we need to, we keep going to the functions that are used by that one

2022-02-11 13:45 UTC, angrykoala commented on packages/graphql/src/classes/Neo4jGraphQL.ts
> +        // this.schemaDefinition.resolvers can either be undefined, IResolvers or IResolvers[]
**nitpick (non-blocking)**: I think this comment is not too relevant, types should already make that clear

2022-02-11 13:45 UTC, angrykoala commented on packages/graphql/src/classes/Neo4jGraphQL.ts
> +        }
**suggestion:** I just though we could use `asArray` here:

```suggestion
        const allResolvers=[resolvers, ...asArray(this.schemaDefinition.resolvers)];
```

2022-02-11 13:45 UTC, angrykoala commented on packages/graphql/src/classes/Neo4jGraphQL.ts
> +        });
**suggestion (non-blocking)**: I know it may be pushing a bit, but it could be sooo nice
```suggestion
    return addDefaultResolvers(schema)
```

2022-02-11 15:32 UTC, merged