Explain how to install plugins for people unfamiliar with Neo4j
neo4j/graphql pull request #943
Opened 2022-02-07 20:02 UTC by catherineluse

# Description

This docs change would help me install the required plugin to be able to use DateTimes.

# Issue

[Please provide a link to the GitHub issue in which the proposal for this work was discussed below. ](https://github.com/neo4j/graphql/issues/941)

It's important that changes are discussed in advance to make sure we choose the right solution and to avoid duplication of effort.

Closes:

- 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

2022-02-08 13:55 UTC, darrellwarde commented
Hey @catherineluse, thanks for the contribution, but I'm not such a fan of pointing this out as it's very specific to Neo4j Desktop. If we need to link to this, it would be preferably to a page like https://neo4j.com/labs/apoc/4.4/installation/ which covers all bases.

2022-02-09 03:49 UTC, catherineluse commented
I have updated the PR and signed the CLA

2022-02-09 09:42 UTC, darrellwarde requested changes
This will render quite funny as it is, so will just move this down a couple of lines.

2022-02-09 09:42 UTC, darrellwarde commented on docs/modules/ROOT/pages/introduction.adoc
```suggestion
2. https://nodejs.org/en/[Node.js] 12+

For help installing the APOC plugin, see https://neo4j.com/labs/apoc/4.4/installation/[this page.]

```

2022-02-09 09:45 UTC, darrellwarde approved these changes

2022-02-09 09:57 UTC, merged